export const ADD_PRODUCT ='ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

//register the new type to bring all the products:

export const LIST_ALL_PRODUCTS = 'LIST_ALL_PRODUCTS';
export const LIST_ALL_PRODUCTS_SUCCESS = 'LIST_ALL_PRODUCTS_SUCCESS';
export const LIST_ALL_PRODUCTS_ERROR = 'LIST_ALL_PRODUCTS_ERROR';

//Delete products

export const FETCH_PRODUCT_DELETE = 'FETCH_PRODUCT_DELETE';
export const FETCH_PRODUCT_DELETE_SUCCESS = 'FETCH_PRODUCT_DELETE_SUCCESS';
export const FETCH_PRODUCT_DELETE_ERROR = 'FETCH_PRODUCT_DELETE_ERROR';

//Edit product

export const FETCH_PRODUCT_EDIT = 'FETCH_PRODUCT_EDIT';
export const FETCH_PRODUCT_EDIT_SUCCESS = 'FETCH_PRODUCT_EDIT_SUCCESS';
export const FETCH_PRODUCT_EDIT_ERROR = 'FETCH_PRODUCT_EDIT_ERROR';